### PR TITLE
Removed old docs, Added v4 postman and swagger collection, Updated index.html

### PR DESCRIPTION
**Pull request by simonsagstetter**
- Removed old docs by removing outdated postman collection and environment (Legacy docs still available as release)
- Added new postman collection and environment and swagger.json containing the current Kickbase API v4 documentation
- Updated the index.html to be a browseable swagger ui web version with the new endpoints
- Updated README

### CODE REVIEW

**Comment by simonsagstetter** [comment]
@kevinskyba @casudo if all looks good to you just give the comment a thumbs up. I know would like to merge this asap as I took down my repos gh page and marked it as not activly maintained :) Thanks!

**Review by casudo — APPROVED** [review]
lgtm

**Review by kevinskyba — APPROVED** [review]

**Comment by simonsagstetter** [comment]
@kevinskyba can you initiate the gh page deployment of the repo because commit did not auto trigge it and old page ist still up?

**Comment by kevinskyba** [comment]
@simonsagstetter Done, some weird change now requires a .nojekyll file in the root folder to be published by gh pages (https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site) if not using gh actions for publishing. I've added it and now it works.

**Comment by simonsagstetter** [comment]
> @simonsagstetter Done, some weird change now requires a .nojekyll file in the root folder to be published by gh pages (https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site) if not using gh actions for publishing. I've added it and now it works.

alright, thanks for the quick fix!

**Pull request merged**
